<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/1eea0c00ae.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Aladin&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../../public/ressources/css/style.css">
    <title>Médecine traditionelle chinoise-XIAO YU</title>
</head>

<body>
    <header>
        <nav>
            <ul>
                <li class="logo"><a href="index.php"><img src="../../public/ressources/images/logo.jpg" alt=""></a></li>
                <div class="nav-link">
                    <li><a href="#title-history">Qu'est ce que la médecine chinoise</a></li>
                    <li><a href="#title-performance">Prestations</a></li>
                    <li><a href="#title-contact">Me contacter</a></li>
                </div>
            </ul>
        </nav>
    </header>
    <section class="bg-image">
        <h1>Xiao Yu prend soin de vous</h1>
    </section>
    <section class="history-mtc">
        <div class="title-history" id="title-history">
            <h2>La médecine traditionelle chinoise</h2>
        </div>
        <p>
            La médecine traditionelle chinoise (MTC) existe depuis des millénaires. Elle s'appuye sur le "Qi" (se prononce"chi") qui est le fondement de la médecine chinoise, il représente l'energie vitale de notre corps. Il peut arriver que cette énergie soit déséquilibrée alors la MTC utilise diverses techniques pour que le corps soit de nouveau en harmonie avec son qi.<br />La pratique la plus connue pour la stimulation du corps est l'acupuncture, cependant il existe d'autres moyens comme les massages TuiNa, la réflexiologie plantaire, les ventouses ou la moxibution (stimulation des points d'acupuncture par la chaleur à l'aide de moxas).<br />Lors d'une consultation le praticien réalise au préalable un bilan énergétique afin de mieux connaître son patient et ainsi savoir quels sont ses blocages énergétiques et quelle méthode serait la plus adaptées pour le soulager.<br />Le praticien peut également prescrire de la pharmacopée (synergie de plantes).
        </p>
    </section>
    <section class="performances">
        <div class="title-performance" id="title-performance">
            <h2>Mes services</h2>
        </div>
        <div class="all-cards">
            <div class="card-performance">
                <img src="../../public/ressources/images/prestation3.jpeg" alt="" class="image-performance">
                <div class="middle">
                    <a href="performances.php?#title-cs" class="text">En savoir plus</a>
                </div>
                <h3>Consultation</h3>
            </div>
            <div class="card-performance">
                <img src="../../public/ressources/images/prestation1.jpeg" alt="" class="image-performance">
                <div class="middle">
                    <a href="performances.php?#title-mt" class="text">En savoir plus</a>
                </div>
                <h3>Massage TuiNa</h3>
            </div>
            <div class="card-performance">
                <img src="../../public/ressources/images/prestation2.jpeg" alt="" class="image-performance">
                <div class="middle">
                    <a href="performances.php?#title-a" class="text">En savoir plus</a>
                </div>
                <h3>Acupuncture</h3>
            </div>
            <div class="card-performance">
                <img src="../../public/ressources/images/prestation4.jpeg" alt="" class="image-performance">
                <div class="middle">
                    <a href="performances.php?#title-rp" class="text">En savoir plus</a>
                </div>
                <h3>Réflexologie plantaire</h3>
            </div>
        </div>
    </section>
    <section class="contact">
        <div class="title-contact" id="title-contact">
            <h2>Contact</h2>
        </div>
        <div class="emoticons">
            <i class="fas fa-mobile-alt"></i>
            <i class="fas fa-map-marker-alt"></i>
            <i class="fas fa-at"></i>
        </div>
        <div class="items-contact">
            <ul>
                <li class="phone">Appelez moi au :<br> 06.61.86.63.90</li>
                <li class="adress">Lieu de pratique :<br> 3 rue du château - Ecuelle <br> 54770 Bouxières-aux-chênes</li>
                <li class="email">Mon email :<br>bea.cunat@orange.fr</li>
            </ul>
        </div>
        <form action="" method="">
            <div class="textarea-button">
                <textarea name="" id="" cols="40" rows="5" placeholder="Message*"></textarea>
                <a href="" class="send">Envoyer</a>
            </div>
            <div class="input-link">
                <input type="text" name="" id="" placeholder="Nom*" class="name">
                <input type="text" name="" id="" placeholder="Prénom*" class="forename">
                <input type="text" name="" id="" placeholder="Email*" class="mail">
            </div>
            <div class="map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2629.2484239725104!2d6.2660879152036975!3d48.777147379279626!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x479496bbb2143c21%3A0x495c424a4fef198a!2s3%20Rue%20du%20Ch%C3%A2teau%2C%2054770%20Bouxi%C3%A8res-aux-Ch%C3%AAnes!5e0!3m2!1sfr!2sfr!4v1595576782921!5m2!1sfr!2sfr" width="400" height="250" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
            </div>
        </form>
    </section>
    <footer>
    </footer>
</body>

</html>