<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/1eea0c00ae.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Aladin&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../../public/ressources/css/performances.css">
    <title>Médecine traditionelle chinoise-XIAO YU-prestations</title>
</head>

<body>
    <header>
        <nav>
            <ul>
                <li class="logo"><a href="index.php"><img src="../../public/ressources/images/logo.jpg" alt=""></a></li>
                <div class="nav-link">
                    <li><a href="../../application/controllers/index.php?#title-history">Qu'est ce que la médecine chinoise</a></li>
                    <li><a href="../../application/controllers/index.php?#title-performance">Prestations</a></li>
                    <li><a href="../../application/controllers/index.php?#title-contact">Me contacter</a></li>
                </div>
            </ul>
        </nav>
    </header>
    <section class="bg-image">
        <h1>Tarifs des prestations</h1>
    </section>
    <section class="performances">
        <div class="performance-one">
            <div class="title-cs" id="title-cs">
                <h2>Consultation</h2>
            </div>
            <div class="image">
                <img src="../../public/ressources/images/prestation3.jpeg" alt="">
            </div>
            <div class="description">
                <p></p>
            </div>
            <ul>
                <li>Bilan énergétique + acupuncture : 45 €</li>
            </ul>
        </div>
        <div class="performance-two">
            <div class="title-mt" id="title-mt">
                <h2>Massage TuiNa</h2>
            </div>
            <div class="image">
                <img src="../../public/ressources/images/prestation1.jpeg" alt="">
            </div>
            <div class="description">
                <p>C’est un ensemble de techniques manuelles que le praticien peut utiliser dans un objectif de bien-être mais également pour soulager certains maux tels que les céphalées, les troubles du cycle chez la femme, les désordres digestifs, les troubles musculo-tendineux, l’insomnie …. </p>
            </div>
            <ul>
                <li>Massage TuiNa corps + visage: 50 € (1 heure)</li>
                <li>Massage TuiNa dos: 45 € (40 min)</li>
                <li>Massage TuiNa visage: 35 € (30 min)</li>
            </ul>
        </div>
        <div class="performance-three">
            <div class="title-a" id="title-a">
                <h2>Acupuncture</h2>
            </div>
            <div class="image">
                <img src="../../public/ressources/images/prestation2.jpeg" alt="">
            </div>
            <div class="description">
                <p>L'acupunture est une pratique qui vise à maintenir une bonne circulation d'énergie en la tonifiant au travers l'utilisation d'aiguilles ou de points de pression.</p>
            </div>
            <ul>
                <li class="only-price">Lifting visage par acupunture: 55 € (1 heure)</li>
            </ul>
        </div>
        <div class="performance-four">
            <div class="title-rp" id="title-rp">
                <h2>Réflexologie plantaire</h2>
            </div>
            <div class="image">
                <img src="../../public/ressources/images/prestation4.jpeg" alt="">
            </div>
            <div class="description">
                <p>La Réflexologie plantaire est un massage profond des pieds dans le but d'améliorer la circulation énergétique dans les méridiens.</p>
            </div>
            <ul>
                <li class="only-price">Réflexologie plantaire: 45 € (1 heure)</li>
            </ul>
        </div>
    </section>
    <footer>
    </footer>
</body>

</html>